services:
  web:
    build: ./web
    ports:
      - "8777:8777"
    volumes:
      - ./web/:/web/
    env_file:
      - .env
    environment:
      DATABASE_USER: "${DATABASE_USER}"
      DATABASE_PASSWORD: "${DATABASE_PASSWORD}"
      DATABASE_PORT: "${DATABASE_PORT}"
      DATABASE_DB: "${DATABASE_DB}"

  pgweb:
    restart: always
    image: sosedoff/pgweb
    ports:
      - 8081:8081
    env_file:
      - .env
    environment:
      PGWEB_DATABASE_URL: postgres://${DATABASE_USER}:${DATABASE_PASSWORD}@db:${DATABASE_PORT}/${DATABASE_DB}?sslmode=disable
    depends_on:
      - postgredb

  postgredb:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
    postgres_data:
