
[tool.basedpyright]
include = ["./*"]
exclude = ["**/node_modules",
    "**/__pycache__",
    "src/experimental",
    "src/typestubs"
]
# ignore = [""]
defineConstant = { DEBUG = true }
stubPath = "src/stubs"

# reportMissingImports = true

pythonVersion = "3.11"
pythonPlatform = "Linux"
# reportGeneralTypeIssues = false

# basedpyright errors and warnings
reportMissingTypeStubs = "warning"

reportUnusedVariable = "warning"
reportUnusedImport = "warning"

reportAny = false


reportUnknownMemberType = "warning"
reportUnknownParameterType = false
reportUnknownVariableType = false

reportCallInDefaultInitializer = false

executionEnvironments = [
  { root = "web" }
]
